### PR TITLE
Add `PluginDirPath` for `LuaRuntime`

### PR DESCRIPTION
**Pull request by Chance-fyi**
PHP's compilation process is so complex that I wrote a shell script for it, which can be found and executed via `PluginDirPath`. 
Or is there another way to execute the shell script?

### CODE REVIEW

**Comment by aooohan** [comment]
There seems to be no better solution. : |

**Review by aooohan — APPROVED** [review]

**Comment by aooohan** [comment]
@Chance-fyi As a reminder, remember to note this on plugin-template and docs.

**Comment by Chance-fyi** [comment]
When will the new version be released?

**Comment by aooohan** [comment]
> When will the new version be released?

As soon as this afternoon.

**Pull request merged**
