### PR TITLE
feat: add config operation, config ls, config storage --sdk-path=D:/vfox/

### PR DESCRIPTION
**Pull request by cifaz**
add config operation, config ls, config storage --sdk-path=D:/vfox/
command:
```
vfox config ls
vfox config storage --sdk-path=D:/vfox
```

### CODE REVIEW

**Comment by Chance-fyi** [comment]
Perhaps it could support all configurations, not just `sdkPath`, similar to `git config`.

**Comment by aooohan** [comment]
Is setting the configuration through commands really simpler than modifying the configuration file directly? 

What if we want to cancel the original configuration? Do we need to add the `--unset` option?

**Comment by cifaz** [comment]
> Perhaps it could support all configurations, not just `sdkPath`, similar to `git config`.

Now, the configs contains proxy, storage and register; 
Want all support?
```
vfox proxy --url=http://xx.com
vfox proxy -- enable=true
vfox registry --address=http://xx.com
```

other command
show the vfox run path
```
vfox config path
```

> Is setting the configuration through commands really simpler than modifying the configuration file directly?
> 
> What if we want to cancel the original configuration? Do we need to add the `--unset` option?

First of all, when I use vfox, I really feel confus that I donot know where are the config path;

I often set a frequently used sdkPath, firstly for easy access, and secondly because some SDKs tend to become larger in size. By using commands, I can install VFox, set corresponding parameters, and install the necessary SDKs without switching tools.

command --unset is good option; I have no idea how to realize him; Set default config file or config strut to reset them?

**Comment by aooohan** [comment]
> ```
> vfox proxy --url=http://xx.com
> vfox proxy -- enable=true
> vfox registry --address=http://xx.com
> ```
> 
> other command show the vfox run path
> 
> ```
> vfox config path
> ```
> 

I don't like any of the above command designs, and if I were to do this, I'd prefer the following command design:
```shell
vfox config proxy.enable true
vfox config proxy.url http://xxxx

vfox config registry.address http://localhost

vfox config --unset registry.address

```
It might be a little more troublesome to implement.



> command --unset is good option; I have no idea how to realize him; Set default config file or config strut to reset them?

Only reset targeted property to default value. For example, `vfox config --unset registry.address` will reset `registry.address` property to 
https://github.com/version-fox/vfox/blob/8abc625fef9d6ee419f7896f9bc592b98091d3f0/internal/config/registry.go#L23-L25

**Comment by cifaz** [comment]
> > ```
> > vfox proxy --url=http://xx.com
> > vfox proxy -- enable=true
> > vfox registry --address=http://xx.com
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > other command show the vfox run path
> > ```
> > vfox config path
> > ```
> 
> I don't like any of the above command designs, and if I were to do this, I'd prefer the following command design:
> 
> ```shell
> vfox config proxy.enable true
> vfox config proxy.url http://xxxx
> 
> vfox config registry.address http://localhost
> 
> vfox config --unset registry.address
> ```
> 
> It might be a little more troublesome to implement.
> 
> > command --unset is good option; I have no idea how to realize him; Set default config file or config strut to reset them?
> 
> Only reset targeted property to default value. For example, `vfox config --unset registry.address` will reset `registry.address` property to
> 
> https://github.com/version-fox/vfox/blob/8abc625fef9d6ee419f7896f9bc592b98091d3f0/internal/config/registry.go#L23-L25

Example: 
```
config --unset-all
config --unset proxy.url
config --unset proxy.enable
config --unset storage.sdk-path
config --unset registry.address

config proxy.url http://x.com
config proxy.url ""

config proxy.enable true
config proxy.enable false

config storage.sdk-path D:/app/vfox/sdk
config storage.sdk-path ""

config registry.address http://x.com
config registry.address ""
```

**Comment by Chance-fyi** [comment]
This is not the effect I want. I want something like `git config`, without needing to set subcommands.

**Comment by cifaz** [comment]
> This is not the effect I want. I want something like `git config`, without needing to set subcommands.

Do you want to the effect like `vfox config proxy.enable=true`

I really refer to the git config; This effect tha command plugin is not supported. 
The git config effect have to parse it by yourself, so I implemented this format first.

**Comment by cifaz** [comment]
> This is not the effect I want. I want something like `git config`, without needing to set subcommands.

Now, support 2 styles like
```
vfox config proxy.enable=true
vfox config proxy.enable true
```

**Comment by Chance-fyi** [comment]
It's different from what I had in mind. If you don't mind, can I implement a version according to my own ideas? We can then compare them.

**Comment by cifaz** [comment]
> It's different from what I had in mind. If you don't mind, can I implement a version according to my own ideas? We can then compare them.

Yes, that's better. I can learn, too

**Comment by aooohan** [comment]
Closing in favor of PR #211

**Pull request closed without merging**
