### PR TITLE
refactor: use shims instead of direct operations on PATH

### LINKED ISSUE #84: Feature: Add a soft link to current version of sdk
We can get the current version through a fixed directory, which can be used in the IDE configuration
Example:
```
~/.version-fox/cache/go/current -> ~/.version-fox/cache/go/v-1.22.1/golang-1.22.1
```

### LINKED ISSUE #235: [BUG]: The recently used plugin should be placed at the beginning of the Path
**Version**
0.4.1

**OS**
macOS、Linux、Windows

**Describe the bug**
Now, since a plugin may be installed with different aliases, the recently used plugins should always be placed at the beginning of the Path environment variable.

### LINKED ISSUE #253: [BUG]: Failed to switch environment in external bash script file
**Version**
0.4.2
**OS**
Linux

**Describe the bug**
在bash脚本中使用 vfox use -s java@17.0.2+8，打印出来还是之前版本的jdk

## 默认版本
image

## 创建一个demo.sh脚本，内容如下
image
打印结果如下，没有成功切换版本

image

### PR DESCRIPTION
**Pull request by aooohan**
fix #253 
fix #84 
fix  #235 
fix version-fox/vfox-golang#9

Instead of modifying the `PATH` directly, this change uses the fixed path `$VFOX_HOME/shims` and `$VFOX_SHELL_TMEP/shims` instead. 

Currently, the way to generate shim is very violent, later we need to ask plugins to tell `vfox` what bins need to be generated shim. see https://github.com/version-fox/vfox/discussions/191#discussioncomment-9064948

### CODE REVIEW

**Comment by aooohan** [comment]
image

**Comment by aooohan** [comment]
image

**Review by bytemain — APPROVED** [review]

**Comment by aooohan** [comment]
There's a problem on Windows, so change this to a draft.

**Comment by jan-bar** [comment]
> There's a problem on Windows, so change this to a draft.

As I expected the directory to be the link instead of the executable file, many tools' executable programs will depend on the directory they are in.

Just like https://github.com/Schniz/fnm

**Comment by aooohan** [comment]
> As I expected the directory to be the link instead of the executable file, many tools' executable programs will depend on the directory they are in.

Yes.  It's not that big of a problem, we can just implement the program exactly as mentioned in #84.

**Comment by jan-bar** [comment]
> Yes. It's not that big of a problem, we can just implement the program exactly as mentioned in #84.

I like the soft link directory solution very much. I have used several version management tools using this method and it works well. I look forward to this implementation.

**Comment by aooohan** [comment]
image

The problem on Windows has been solved, and the original plan is still used.

**Review by bytemain — APPROVED** [review]

**Pull request merged**
