### PR TITLE
Support for searching in all versions

### PR DESCRIPTION
**Pull request by Chance-fyi**
The current functionality only supports searching within the current page and finding results by turning pages. This PR implements the capability to search across all versions.

### CODE REVIEW

**Comment by aooohan** [comment]
image

Is this normal? Why does 12.x version appear?

**Comment by Chance-fyi** [comment]
> Is this normal? Why does 12.x version appear?

I'm still using the original search method and I think the results are correct, but the ordering of the results could be optimized a bit more and I'm working on that!

**Comment by Chance-fyi** [comment]
Before:

image

After:

image

**Review by aooohan — APPROVED** [review]

**Comment by aooohan** [comment]
@Chance-fyi  Hi, I would like to invite you to join `VersionFox` as a committer. Are you interested?

**Comment by Chance-fyi** [comment]
@aooohan Yes, I'm interested in joining VersionFox as a committer. Thank you for the invitation!

**Pull request merged**
