### PR TITLE
add a json flag in `vfox env` subcommand

### PR DESCRIPTION
**Pull request by axdank**
hello, I have added a flag to get the paths in JSON format.

use cases:

```sh
vfox_data=$(vfox env --json)

for path in $(echo "$vfox_data" | jq -r '.paths[]'); do
    export PATH="$PATH:$path"
done

for sdk_name in $(echo "$vfox_data" | jq -r '.sdks | keys_unsorted[]'); do
    for var_name in $(echo "$vfox_data" | jq -r ".sdks.$sdk_name | keys_unsorted[]"); do
        export "$var_name"=$(echo "$vfox_data" | jq -r ".sdks.$sdk_name.\"$var_name\"")
    done
done
```

### CODE REVIEW

**Comment by aooohan** [comment]
What is the purpose of this change? The env command will eventually be translated to correspond command in the corresponding shell, so why add the json format?

**Comment by axdank** [comment]
I based on the use of `fnm` which is a version manager for node, for example fnm env allows you like vfox, to export for a specific shell, or in --json format, so that everyone can implement it in their own way, or if there is no supported shell, as in this case it could be nushell.

image
image

**Comment by aooohan** [comment]
> in --json format, so that everyone can implement it in their own way, or if there is no supported shell, as in this case it could be nushell.

Good point. Thanks for your reply.

**Review by aooohan — APPROVED** [review]
LGTM.

**Pull request merged**
